#!/usr/bin/env python
# -*- coding: utf-8 -*-

# what to happent when running this script
if __name__ == '__main__':
    print('this are my functions in lib file get_wordnet_pos and part_of_speech')

